version: "3.8"
services:
  rstudio:
    image: ${IMAGE_NAME:-rproject:latest}
    build:
      context: docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
    volumes:
      - .:${PROJECT_MOUNT_PATH:-/home/rstudio/rproject}
      - ${DOTFILES_ROOT}:/home/rstudio/dotfiles
      - ${RENV_PATHS_CACHE}:/home/rstudio/.local/share/renv/cache
      - ${GITHUB_SSH_IDENTITY}:/home/rstudio/.ssh/id_github:ro
