version: "3.8"
services:
  rstudio:
    build:
      context: ./docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - ${PROJECT_PATH_HOST:-..}:${PROJECT_PATH_CONTAINER:-/home/rstudio/project}
      - ${RENV_PATHS_CACHE_HOST:-./data/renv/cache}:/home/rstudio/.local/share/renv/cache
      - ${SSH_AUTH_SOCK_HOST:-/dev/null}:/run/host-services/ssh-auth.sock
      - ${DOTFILES_DIR_HOST:-./dotfiles}:${DOTFILES_DIR_CONTAINER:-/home/rstudio/.dotfiles}
      - ./scripts:/scripts
    command: ["sh", "-c", "bash /scripts/before-init.sh && /init"]
